@startuml

title "Attaque d'un personnage a vers un personnage b"

participant "a : Personnage" as a
participant "b : Personnage" as b

-> a : attaquer(b)
activate a
a -> b : diminuerVie(3)
activate b
a <-- b
deactivate b
<-- a
deactivate a

@enduml