@startuml
title "Augmenter vie d'un personnage"

participant "personnage : Personnage" as personnage



-> personnage  : augmenterVie(7)
personnage  -> personnage  : setPv(5+7)
<-- personnage
deactivate personnage
@enduml