@startuml

title "Régénération d'un troll"

participant "troll : Troll" as troll




-> troll : seRegenerer()
activate troll
alt ! attaqueDansLeTour
troll -> troll : augmenterVie(1)
else
end
<-- troll
deactivate troll

@enduml