@startuml

title Diagramme de Classe - Zeldiablo V1

interface Jeu{
    + evoluer(d : Direction)
    + etreFini() : boolean
}

class JeuPerso extends Jeu{
    - partieEnCours : boolean
    + JeuPerso()
    + evoluer(d : Direction)
    + etreFini() : boolean
    + getJoueur() : Joueur
    + getLabyrinthe() : Labyrinthe
}

class Controleur implements KeyListener{
    + Controleur()
    + getDirection() : Direction
    + keyTyped(KeyEvent e)
    + keyPressed(KeyEvent e)
    + keyReleased(KeyEvent e)
}

interface DessinJeu{
    + dessiner(image : BufferedImage)
}

class DessinPerso implements DessinJeu{
    - TAILLE_CASE : int
    + DessinPerso(j : JeuPerso)
    - dessinerObjet(s : String, x : int, y : int, im : BufferedImage)
    + dessiner(im : BufferedImage)
}

class InterfaceGraphique{
    + InterfaceGraphique(afficheurUtil : DessinJeu, x : int, y : int)
    + getControleur() : Controleur
    + dessiner()
}

class MoteurRendu{
    + MoteurRendu(pJeu : Jeu, pAffiche : DessinJeu)
    + lancerJeu(width : int, height : int)
}

class PanelDessin(){
    - imageSuivante : BufferedImage
    - imageEnCours : BufferedImage
    - width : int
    - height : int
    + PanelDessin(x : int, y : int, affiche : DessinJeu)
    + dessinerJeu()
    + paint(g : Graphics)
}

abstract class Personnage{
    - pv : int
    - degats : int
    //POSSEDE Labyrinthe (position : Case)
    + Personnage(l : Labyrinthe, depart : Case, pdv : int, deg : int)
    + setPosition(position : Case)
    + getCase() : Case
    + seDeplacer(d : Direction) : boolean
    + diminuerVie(vieDown : int)
    + augmenterVie(vieUp : int)
    + getPv() : int
    + setPv(newPv : int)
    + attaquer(p : Personnage)
}

class Labyrinthe{
    + Labyrinthe()
    + Labyrinthe(lab : String)
    + deplacerJoueur(p : Personnage, d : Direction) : boolean
    - peutBouger(p : Personnage, d : Direction) : boolean
    - getDestination(p : Personnage, d : Destination) : Case
    + getJoueur() : Joueur
    + toString() : String
    + getEntree() : Porte
    + getSortie() : Porte
    + getCase(x : int, y : int) : Case
    + getCases() : Case[][]
}

abstract class Case{
    - x : int
    - y : int
    + Case(x : int, y : int)
    + peutTraverser(p : Personnage) : boolean
    + getIdentifier() : String
    + toString() : String
}

class Chemin extends Case{
    - identifier : char
    + Chemin(x : int, y : int)
    + peutTraverser(p : Personnage) : boolean
    + getIdentifier() : String
}

abstract class Obstacle extends Case{
    + Obstacle(x : int, y : int)
    + peutTraverser(p : Personnage) : boolean
}

class Mur extends Obstacle{
    - identifier : char
    + Mur(x : int, y : int)
    + peutTraverser(p : Personnage) : boolean
    + getIdentifier() : String
}

class Porte extends Case{
    - identifier : char
    - ferme : boolean
    + Porte(x : int, y : int)
    + setFerme(boolean b)
    + peutTraverser(p : Personnage) : boolean
    + getIdentifier() : String
}

class Joueur extends Personnage{
    + Joueur(l : Labyrinthe, e : Porte)
}

enum Direction{
    NORTH
    SOUTH
    EAST
    WEST
}

abstract class Monstre extends Personnage{
    + Monstre(l : Labyrinthe, depart : Case, pdv : int, deg : int)
}

class Troll extends Monstre{
    - tapeDansLeTour : boolean
    + Troll(l : Labyrinthe, depart : Case)
    + seRegenerer() : void
    //TODO + seFaireAttaquer()
}

class Fantome extends Monstre{
    + Fantome(l : Labyrinthe, depart : Case)
}

Jeu "1" --> "1" Labyrinthe: " - labyrinthe"
Labyrinthe "1" -down-> "1" Porte: " - entree "
Labyrinthe "1" -left-> "1" Porte: " - sortie "
Labyrinthe "1" --> "*" Case: " - cases "
Personnage "*" --> "1" Case: " - position "
Personnage "*" --> "1" Labyrinthe: " - l "
Labyrinthe "1" -left-> "1" Joueur: " - joueur "






PanelDessin "1" -> "1" DessinJeu : "- dessin"
DessinPerso "1" -> "1" JeuPerso : "- jeuEnCours"
JeuPerso "1" -> "1" Labyrinthe : "- l"
JeuPerso "1" -> "1" Joueur : "- pj"
Controleur "1" -> "1" Direction : "- enCours"
Controleur "1" -> "1" Direction : "- aRetourner"
MoteurRendu "1" -> "1" Jeu : "- jeu"
MoteurRendu "1" -> "1" InterfaceGraphique : "- gui"
MoteurRendu "1" -> "1" DessinJeu : "- dessin"
InterfaceGraphique "1" -> "1" Controleur : "- controleur"
InterfaceGraphique "1" -> "1" PanelDessin : "- panel"


@enduml