@startuml

title "Déplacement d'un joueur"

participant "j : Jeu" as j
participant "p1 : Personnage" as p1
participant "l : Labyrinthe" as l

activate j
j -> p1 : seDeplacer(Directions.NORTH)
activate p1
p1 -> l : deplacerJoueur(p1, Directions.NORTH)
activate l
l -> l : peutBouger(p1, Directions.NORTH)
alt true
    l -> l : getDestination(p1, Directions.NORTH)
    l --> l : case
    l -> p1 : setPosition(case)
    p1 --> l : true
end
l --> p1 : true
deactivate l
p1 --> j : true
deactivate p1
deactivate j

@enduml